import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import ParticlesBG from './components/ParticlesBG'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en-US">
      <body className={inter.className + " relative flex justify-center bg-primary-light dark:bg-primary-dark text-text-light dark:text-text-dark"}>
        <div className='max-w-5xl w-full'>

          <Navbar />
          <ParticlesBG />

          <Theme>
            {children}
          </Theme>

          {/* Footer */}
          <div className='mt-12'>
            <Footer />
          </div>

        </div>
      </body>
    </html>
  )
}
